//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuntikirjaus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henkilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Henkilo()
        {
            this.Tuntikirjaukset = new HashSet<Tuntikirjaus>();
        }
    
        public int henkilo_id { get; set; }
        public string etunimi { get; set; }
        public string sukunimi { get; set; }
        public int osasto_id { get; set; }
        public string tehtavanimike { get; set; }
    
        public virtual Osasto Osasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuntikirjaus> Tuntikirjaukset { get; set; }
    }
}
