//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuntikirjaus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuntikirjausEntities : DbContext
    {
        public TuntikirjausEntities()
            : base("name=TuntikirjausEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Henkilo> Henkilot { get; set; }
        public virtual DbSet<Osasto> Osastot { get; set; }
        public virtual DbSet<Projekti> Projektit { get; set; }
        public virtual DbSet<Tuntikirjaus> Tuntikirjaukset { get; set; }
    }
}
